<?php

use le7\Core\User\UserInterface;
use le7\Core\Helpers\UrlHelper;
use le7\Core\View\Php\PhpView;

/** @var UserInterface $user */
/** @var PhpView $this */
/** @var UrlHelper $url */
$this->setStyleLib('bootstrap5/dist/css/bootstrap.css');
?>
<!DOCTYPE html>
<html lang="<?php echo $lang ?>">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta http-equiv="X-UA-Compatible" content="ie=edge">
        <meta name="description" content="<?php echo $this->e($description); ?>">
        <meta name="keywords" content="<?php echo $this->e($keywords); ?>" />
        <title><?= $this->e($title); ?> - <?php echo $config->getProjectName() ?></title>
        <?php echo $styles; ?>
        <?php echo $env ?>
        <?php echo $scripts_header; ?>
        <?php echo $snippets_top; ?>
    </head>
    <body>
        <?php echo $snippets_middle; ?>

        <div class="container py-3">
            <header>
                <div class="d-flex flex-column flex-md-row align-items-center pb-3 mb-4 border-bottom">
                    <img class="mb-2" src="<?php echo $urlImages; ?>/logo_red.svg" alt="" width="200">
                    <a href="/" class="d-flex align-items-center text-dark text-decoration-none">
                        <span class="fs-4"><?php echo $this->e($title); ?></span>
                    </a>

                    <nav class="d-inline-flex mt-2 mt-md-0 ms-md-auto">
                        <a class="me-3 py-2 text-dark text-decoration-none" href="<?php echo $url->get(); ?>"><?php echo _('Home') ?></a>
                        <a class="me-3 py-2 text-dark text-decoration-none" href="<?php echo $url->get('doc'); ?>"><?php echo _('Documentation'); ?></a>
                        <?php if (empty($user)): ?>
                            <a class="py-2 text-dark text-decoration-none" href="<?php echo $url->get('login', '', '', 'admin'); ?>"><?php echo _('login'); ?></a>
                        <?php else: ?>
                            <a class="py-2 text-dark text-decoration-none" href="<?php echo $url->get('dashboard', '', '', 'admin'); ?>"><?php echo $user->username; ?></a>
                            <a class="py-2 text-dark text-decoration-none" href="<?php echo $url->get('login', 'logout', '', 'admin'); ?>">(<?php echo _('logout'); ?>)</a>
                        <?php endif; ?>
                    </nav>
                </div>

                <?php foreach ($otherLanguages as $lng): ?>
                    <a href = "<?php echo $lng['url']; ?>"><?php echo $lng['label']; ?></a> 
                <?php endforeach; ?>

            </header>

            <?php foreach ($messages as $message): ?>
                <div class="alert alert-danger" role="alert">
                    <?php echo $message['message']; ?>
                </div>
            <?php endforeach; ?>

            <?php echo $this->include($content); ?>

            <footer class="pt-4 my-md-5 pt-md-5 border-top">
                <div class="row">
                    <div class="col-12 col-md">
                        <img class="mb-2" src="<?php echo $urlImages; ?>/logo_red.svg" alt="" width="200">
                        <small class="d-block mb-3 text-muted">&copy; 2017–2023</small>
                    </div>
                    <div class="col-6 col-md">
                        <h5><?php echo _('Documentation'); ?></h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Another one</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="#">Last time</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5><?php echo _('Resources'); ?></h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.php.net/">PHP</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://redbeanphp.com">RedbeanPHP</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://php-di.org/">PHP-DI</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://www.smarty.net/">Smarty</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://github.com/Nyholm/psr7">Nyholm PSR7</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="http://phpdebugbar.com/">PHP DebugBar</a></li>
                        </ul>
                    </div>
                    <div class="col-6 col-md">
                        <h5><?php echo _('About'); ?></h5>
                        <ul class="list-unstyled text-small">
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="<?php echo $uconfig->sample->github_link ?? 'https://github.com/rnr1721/le7-framework'; ?>">Github</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="<?php echo $uconfig->sample->packagist_link ?? 'https://packagist.org/packages/rnr1721/le7-framework'; ?>">Packagist</a></li>
                            <li class="mb-1"><a class="link-secondary text-decoration-none" href="https://en.wikipedia.org/wiki/MIT_License">MIT License</a></li>
                        </ul>
                    </div>
                </div>
            </footer>
        </div>

        <?php echo $scripts_footer ?>
        <?php echo $snippets_bottom; ?>
    </body>
</html>
