<main>
    <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
        <h1 class="display-4 fw-normal"><?php echo _('Sample page'); ?></h1>
        <p class="fs-5 text-muted"><?php echo _('Default theme. You can create own.'); ?></p>
        <p class="fs-5 text-muted"><?php echo _('This theme placed in.'); ?> <?php echo $urlTheme; ?>. <?php echo _('You can define your theme in config.ini file'); ?></p>
    </div>
</main>
