; LameEngine config file. Please do not remove any strings from this file
[general]
; script version
scriptVersion = 1;
; Set production or development state
isProduction = false
; Name of project
projectName = "My Sample Project"
; Default controller
defaultController = "index"
; Default action
defaultAction = "index"
; Controller for 404 pagw
notfoundController = "notfound"
; Choose timezone
timeZone = "Europe/Kiev"
; Folder with HTML theme
theme = "main"
; Error Reporting
errorReporting = true
; Var folder for cache/logs/temp etc
dirVar = "var"
; Storage for flash messages - "session" or "cookies"
flashMessageStorage = "cookies"

[sessions]
; Lax or Strict or None
samesite = "Lax"

[api]
allowedMethods = "POST, GET, OPTIONS, PUT, DELETE, HEAD"
allowedHeaders = "Content-Type, Origin, Authorizations, User-Agent, Host, Authorization, Content-Length, Accept, X-Requested-With, X-Auth-Token, Content-Language, Source"

[headers]
; no-referrer, no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
referrerPolicy = "no-referrer-when-downgrade"
contentSecurityPolicy = "default-src 'self' 'unsafe-inline';img-src 'self' data:;font-src 'self'"
strictTransportSecurity = "max-age=7776000"
xContentTypeOptions = "nosniff"
; deny or SAMEORIGIN
xFrameOptions = "SAMEORIGIN"
xXssProtection = "1; mode=block"

[smarty]
leftDelimiter = "{"
rightDelimiter = "}"

[locales]
defaultLanguage = "en"
locales[ru] = "ru_RU|Русский"
locales[en] = "en_US|English"
locales[ua] = "uk_UA|Українська"

[daemon]

[users]
; turn on out-of-box user management
userManagement = true
; unique fields for use as login
userLoginFields = "username"
; "cookies" or "session"
userIdentity = 'cookies'
userLoginVerificationOn = false;
userRegisterVerificationOn = true;
; You can add own methods with comma-separated, for example email,sms

[notification]
; comma-separated
cases = "email"
; Ad own notification classes that implements
; le7\Core\User\Notifications\NotificationInterface
classes[email] = "le7\Core\User\Notifications\NotificationEmailFactory"

[email]
config[active] = "1"
config[html] = true,
config[secure] = "ssl"
config[host] = "smtp.gmail.com"
config[port] = "465"
config[username] = "admin@ehukr.com"
config[password] = "MyGreatPassword777"
config[from_email] = "admin@ehukr.com"
config[from_name] = "Eugeny Gazzaev"
config[charset] = "UTF-8"
config[debug] = "0"

[debug]
; Turn on debug bar in non-production mode
; In production mode debugbar will stay turned off
include = true
; Comma separated IPs to allow debugbar in non-production mode
allowedIp = "127.0.0.1"

[cache]
; Global cache lifetime for HTML pages
; int value or 0 (for permanent cache) ot null for turn off cache
cacheLifetime = 3600
; file or memcache, memcached or redis
default = "file"
memcache_connect = "127.0.0.1:11211"
memcached_connect = "127.0.0.1:11211"
