[database]
; mysql or pgsql
dbdrvr = "mysql"
; user of Db
dbuser = "test"
; db host
dbhost = "localhost"
; db password
dbpass = "test"
; db name
dbname = "test"
; db prefix
dbprfx = ""
; freeze db
dbfreeze = false
